#!/bin/bash
prompt="Please select a file to compile:"
options=( $(find *.c | xargs -0) )

PS3="$prompt "
echo ""
select opt in "${options[@]}" "Quit" ; do
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "Compiling $opt"
        wine c51.exe $opt 2>&1 | grep -v preloader | grep -v fixme
        break

    else
        echo "Invalid option. Try another one."
    fi
done
echo ""
