void ToggleLED(void);
void ToggleLED2(void);
void ToggleLED3(void);
void ToggleLED4(void);
void pwmPower1(int option);
void pwmPower2(int option);
void pwmPower3(int option);
void pwmPower4(int option);
void OneOff(void);
void TwoOff(void);
void ThreeOff(void);
void FourOff(void);
void OneOn(void);
void TwoOn(void);
void ThreeOn(void);
void FourOn(void);