#!/bin/bash
prompt="Please select a file to compile:"
options=( $(find *.hex | xargs -0) )

PS3="$prompt "
echo ""
select opt in "${options[@]}" "Quit" ; do
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "Compiling $opt"
        ./EFM8_prog -r -p/dev/ttyUSB0 $opt
        break

    else
        echo "Invalid option. Try another one."
    fi
done
echo ""
